image: ${CI_REGISTRY_IMAGE}:latest

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

default:
  tags:
    - chs-shared
    - dind

stages:
  - build
  - check
  - test
  - end
  - deploy

variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_SUGGESTS_ONLY: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  _R_CHECK_DONTTEST_EXAMPLES_: "false"
  R_PROFILE: "$R_HOME/etc/Rprofile.site"
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"
  APT_CACHE: "$CI_PROJECT_DIR/ci/lib/apt-cache"
  CRAN: "https://rpkg.chs.usgs.gov/prod-cran/latest"
  R_LIBS: "$CI_PROJECT_DIR/ci/lib"
  BUILD_LOGS_DIR: "$CI_PROJECT_DIR/ci/logs"
  NOT_CRAN: "true"
  PAGES_OUTDIR: "$CI_PROJECT_DIR/public"
  CUSTOM_DR_UA: "GitLab_CI"
  API_USGS_PAT: "${API_USGS_PAT}"

build-image:
  stage: build
  cache: []
  image: ${DEVOPS_REGISTRY}usgs/docker:20
  services:
  - name: ${DEVOPS_REGISTRY}usgs/docker:20-dind
    alias: docker
  rules:
    - changes:
      - docker/Dockerfile
  script:
    - echo ${CI_REGISTRY_PASSWORD} | docker login -u ${CI_REGISTRY_USER} --password-stdin $CI_REGISTRY
    - docker pull ${CI_REGISTRY_IMAGE}:latest || true
    - cd docker
    - docker build
        -t ${CI_REGISTRY_IMAGE}:latest
        .
    - docker push --all-tags ${CI_REGISTRY_IMAGE}

buildcheck:
  stage: check
  cache: []
  dependencies:
    - build-image
  script:
    - Rscript -e 'devtools::install(quick = TRUE, upgrade = "never")'
    - Rscript -e 'devtools::check(document = FALSE, args = "--no-tests", check_dir = Sys.getenv("BUILD_LOGS_DIR"), vignettes = FALSE)'


  
pages:
  stage: end
  dependencies:
    - build-image
    - buildcheck
  script:
    - Rscript -e 'devtools::install(quick = TRUE, upgrade = "never")'
    - Rscript -e 'pkgdown::build_site(override = list(destination = "public"))'
    - Rscript -e 'file.copy(from = "./public/articles/logo.png", to = "./public/reference/logo.png")'
    - quarto render tutorials/changes_slides_deck.qmd --output-dir $PAGES_OUTDIR/tutorials
    - quarto render tutorials/basic_slides_deck.qmd --output-dir $PAGES_OUTDIR/tutorials
  artifacts:
    paths:
      - $PAGES_OUTDIR
    expire_in: 1 week
    
Validate Inventory:
    stage: end
    only: 
      - main
    image: ${INTERNAL_REGISTRY}software/software-management:latest
    script:
      - software-management review
        --project "${CI_PROJECT_PATH}"
        --ref "${CI_COMMIT_BRANCH}"
        --type "provisional"
        --token "${GIT_TOKEN_CUSTOM}"
    tags:
        - chs-shared
