image: code.usgs.gov:5001/water/dockerr:latest

include:
  - template: Code-Quality.gitlab-ci.yml

variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  _R_CHECK_DONTTEST_EXAMPLES_: "false"
  CRAN: "https://rpkg.chs.usgs.gov/prod-cran/latest"
  NOT_CRAN: "true"
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"
  R_LIBS: "$CI_PROJECT_DIR/ci/lib"
  BUILD_LOGS_DIR: "$CI_PROJECT_DIR/ci/logs"
  CONNECT_API_KEY: $CONNECT_API_KEY
  CONNECT_SERVER: $CONNECT_SERVER
  PAGES_OUTDIR: "$CI_PROJECT_DIR/public"

stages:
  - getready
  - check
  - test
  - end
  - deploy

getready:
  stage: getready
  script:
    - mkdir -p $R_LIBS_USER
    - Rscript -e "install.packages(c('rlang', 'stringi', 'devtools','pkgdown', 'connectapi', 'patchwork', 'tidyr', 'data.table'))"
    - Rscript -e "remotes::update_packages()"
    - Rscript -e "devtools::install_deps(dependencies = TRUE, quiet = TRUE)"
  cache:
    paths:
     - $R_LIBS_USER
  artifacts:
    paths:
     - $R_LIBS_USER
     
buildcheck:
  stage: check
  script:
    - mkdir -p $BUILD_LOGS_DIR
    - Rscript -e "devtools::install(build_vignettes = FALSE, args = '--no-manual', upgrade = 'always')"
    - R -e 'devtools::check(document = FALSE, args = "--no-tests", error_on = "error", check_dir = Sys.getenv("BUILD_LOGS_DIR"))'
  artifacts:
    paths:
      - $BUILD_LOGS_DIR

unittests:
  stage: test
  dependencies:
    - getready
    - buildcheck
  script:
    - R -e 'library(testthat); options(testthat.output_file = file.path(Sys.getenv("CI_PROJECT_DIR"), "test-out.xml")); devtools::test(reporter = "junit")'
  artifacts:
    when: always
    paths: 
      - test-out.xml
    reports:
      junit: test-out.xml
        
covertests:
  stage: test
  dependencies:
    - getready
    - buildcheck
  script:
    - R -e 'x <- covr::package_coverage(); covr::to_cobertura(x); x; '
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml
  coverage: '/Coverage: \d+.\d+\%/'

pages:
  stage: end
  only: 
    - main
  script:
    - Rscript -e "library(data.table); library(dataRetrieval)"
    - Rscript -e "devtools::session_info()"
    - Rscript -e 'pkgdown::build_site(override = list(destination = "public"))'
    - Rscript -e 'source("deploy_simple.R")'
  artifacts:
    paths:
      - $PAGES_OUTDIR
    expire_in: 1 week

Validate Inventory:
    stage: end
    image: ${INTERNAL_REGISTRY}software/software-management:latest
    script:
      - software-management review
        --project "${CI_PROJECT_PATH}"
        --ref "${CI_COMMIT_BRANCH}"
        --type "provisional"
        --token "${GIT_TOKEN_CUSTOM}"
    tags:
        - chs-shared
