image: ${CI_REGISTRY_IMAGE}:latest

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

default:
  tags:
    - chs-shared
    - dind

stages:
  - build
  - check
  - test
  - end
  - deploy

variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_SUGGESTS_ONLY: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  _R_CHECK_DONTTEST_EXAMPLES_: "false"
  R_PROFILE: "$R_HOME/etc/Rprofile.site"
  APT_CACHE: "$CI_PROJECT_DIR/ci/lib/apt-cache"
  CRAN: "https://rpkg.chs.usgs.gov/prod-cran/latest"
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"
  R_LIBS: "$CI_PROJECT_DIR/ci/lib"
  BUILD_LOGS_DIR: "$CI_PROJECT_DIR/ci/logs"
  NOT_CRAN: "true"
  PAGES_OUTDIR: "$CI_PROJECT_DIR/public"
  CUSTOM_DR_UA: "GitLab_CI"
  API_USGS_PAT: "${API_USGS_PAT}"

build-image:
  stage: build
  cache: []
  image: ${DEVOPS_REGISTRY}usgs/docker:20
  services:
  - name: ${DEVOPS_REGISTRY}usgs/docker:20-dind
    alias: docker
  rules:
    - changes:
      - docker/Dockerfile
      - .gitlab-ci.yml
  script:
    - echo ${CI_REGISTRY_PASSWORD} | docker login -u ${CI_REGISTRY_USER} --password-stdin $CI_REGISTRY
    - docker pull ${CI_REGISTRY_IMAGE}:latest || true
    - cd docker
    - docker build
        -t ${CI_REGISTRY_IMAGE}:latest
        .
    - docker push --all-tags ${CI_REGISTRY_IMAGE}

buildcheck:
  stage: check
  cache: []
  dependencies:
    - build-image
  script:
    - R CMD build . --no-manual
    - Rscript -e 'devtools::check(document = FALSE, args = "--no-tests", check_dir = Sys.getenv("BUILD_LOGS_DIR"), vignettes = FALSE)'

unittests:
  stage: test
  cache: []
  dependencies:
    - build-image
    - buildcheck
  script:
    - R -e 'library(testthat); options(testthat.output_file = file.path(Sys.getenv("CI_PROJECT_DIR"), "test-out.xml")); devtools::test(reporter = "junit")'
    - R -e 'x <- covr::package_coverage(); covr::to_cobertura(x); x; '
  artifacts:
    when: always
    expire_in: 1 week
    paths: 
      - test-out.xml
    reports:
      junit: test-out.xml
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml
  coverage: '/Coverage: \d+.\d+\%/'

longtest:
  stage: test
  dependencies:
    - build-image
    - buildcheck
  script:
    - Rscript -e 'testthat::test_local(path = "tests/manual")'
  rules:
    - if: $RUN_LONG_TESTS == "FALSE"
      when: always
    - when: never
  
pages:
  stage: end
  cache: []
  script:
    - Rscript -e 'pkgdown::build_site(override = list(destination = "public"))'
    - quarto render tutorials/changes_slides_deck.qmd --output-dir public/tutorials
    - quarto render tutorials/basic_slides_deck.qmd --output-dir public/tutorials
    - Rscript -e 'file.copy(from = "./public/articles/logo.png", to = "./public/reference/logo.png")'
  artifacts:
    paths:
      - $PAGES_OUTDIR
    expire_in: 1 week
    
Validate Inventory:
    stage: end
    only: 
      - main
    image: ${INTERNAL_REGISTRY}software/software-management:latest
    script:
      - software-management review
        --project "${CI_PROJECT_PATH}"
        --ref "${CI_COMMIT_BRANCH}"
        --type "provisional"
        --token "${GIT_TOKEN_CUSTOM}"
    tags:
        - chs-shared


