init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

environment:
  global:
    USE_RTOOLS: true
    WARNINGS_ARE_ERRORS: 1
    NOT_CRAN: "true"
    
  matrix:
  - R_VERSION: devel
    GCC_PATH: mingw_32

  - R_VERSION: release
    R_ARCH: x64

  - R_VERSION: patched
  
matrix:
  fast_finish: true

build_script:
  - travis-tool.sh install_github tidyverse/readr
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits