on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: test-coverage

jobs:
  test-coverage:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@c0a81a463886bb75afe234e07a9fd5bb79219196

      - uses: r-lib/actions/setup-r@756399d909bf9c180bbdafe8025f794f51f2da02

      - uses: r-lib/actions/setup-pandoc@756399d909bf9c180bbdafe8025f794f51f2da02

      - uses: r-lib/actions/setup-r-dependencies@756399d909bf9c180bbdafe8025f794f51f2da02
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
